### PR TITLE
initial support for Alpine Linux (apk)

### PR DESCRIPTION
**Pull request by HRio**
Note that Alpine host code is not implemented in Perl as that is not
present on an Alpine Linux system by default.

Implements ADP 0.6

### CODE REVIEW

**Comment by liske** [comment]
Hi,

there is no requirement to implement the apt-dater-host stuff in Perl. Thanks for your contribution!

**Comment by HRio** [comment]
@jirutka in order to make it similar to Debian, apt-dater-host is usable for members of %adm group in Debian. 

So the account used for apt-dater does not need full sudo access (%sudo on Debian is like %wheel in Alpine).

**Comment by jirutka** [comment]
If it needs root permissions only to run `/sbin/abuild`, then the most appropriate group for this on Alpine is `abuild` group.

**Comment by HRio** [comment]
@jirutka /sbin/apk not abuild, or?

**Comment by jirutka** [comment]
Sry, yes, I meant `/sbin/apk`.

**Comment by jirutka** [comment]
I’m sorry, I’ve been too rushed, need to go sleep. Group `abuild` is used for different purposes, not for running apk.

**Pull request merged**
